# Tomcat
server:
    name: iBase4J-SYS-Service
    port: 8085
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
# mysql
spring:
    # 环境 dev|test|prod
    profiles:
        active: ${spring.profiles.active}
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false